#!/bin/bash
__SYS_PRESEED__="cp /preseed.cfg /target/root; wget -O /target/etc/systemd/system/FIRSTBOOT.service https://raw.githubusercontent.com/rdavid000/AUTOINSTALL/main/startup/FIRSTBOOT.service; wget -O /target/root/FIRSTBOOT.sh https://raw.githubusercontent.com/rdavid000/AUTOINSTALL/main/startup/FIRSTBOOT.sh; chroot /target chmod +x /etc/systemd/system/FIRSTBOOT.service; chroot /target chmod +x /root/FIRSTBOOT.sh; ln -s /target/etc/systemd/system/FIRSTBOOT.service /target/etc/systemd/system/default.target.wants/FIRSTBOOT.service;"
__SYS_HOSTNAME__='IAMPreseed'
__SYS_DOMAIN__=''
__SYS_PROXY__=''
__SYS_PASSWORD__='1234'
__SYS_TIMEZONE__='Europe/Paris'
__SYS_COUNTRY__='FR'
__SYS_LOCAL__='en_US.UTF-8'
__SYS_MIRROR__='ftp.fr.debian.org'
__SYS_GRUB_DRIVE__='/dev/sda'
__INS_FIRMWARE__='http://r.david000.free.fr/firmware-realtek_0.36_all.deb'
__INS_ISO__='debian-11.6.0-amd64-netinst'
__NET_IP__='192.168.200.5'
__NET_MASK__='255.255.255.0'
__NET_GW__='192.168.200.1'
__NET_DNS__='192.168.200.1'
